env GS_BUCKET;
env INDEX;

load_module /usr/lib/nginx/modules/ngx_http_perl_module.so;

events {
    # Event settings
}

http {
    # Enable caching
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

    open_file_cache max=1024 inactive=10s;

    open_file_cache_valid 60s;

    open_file_cache_min_uses 2;

    open_file_cache_errors on;

    gzip on;

    server {
        listen 80;
        server_name _ ;

        # Path to the mounted GCS bucket
        root /mnt/gcp-bucket;

        location / {
            # Serve static files from the bucket
            try_files $uri $uri/ =404;

            # Enable caching for static files
            proxy_cache my_cache;
            proxy_cache_valid 200 1h;
            proxy_cache_valid 404 1m;
            add_header X-Proxy-Cache $upstream_cache_status;

            # Headers for caching
            expires 1h;
            add_header Cache-Control "public";
        }

        # Log files
        access_log /var/log/nginx/bucket_access.log;
        error_log /var/log/nginx/bucket_error.log;
    }
}
